/**
 * Content library for whimsy posts. Two pools, per the resolved hybrid design:
 *
 * - Pool A (large, directive-only): extracted from user-supplied reference material
 *   (example batches), sign stripped (sign is chosen independently — see
 *   composeWhimsyPost.ts), deduplicated, and checked against the content-boundary list in
 *   spec §9.7. Used standalone, no punchline. Also holds the feature's
 *   original two example lines verbatim as fixed compound entries ("buy new socks. Your feet
 *   deserve a plot twist", "delete one screenshot. You know which one") — their punchlines are
 *   specific callbacks to their own directive, so they can't join Pool B's cross-compatible pool
 *   without producing nonsense pairings (e.g. "delete one screenshot. Your feet deserve a plot
 *   twist.") — a bug caught after the first version of this file shipped both as separate,
 *   freely-recombinable Pool B entries.
 * - Pool B (small, ~10x10, cross-compatible): freshly authored so any directive can pair with
 *   any punchline without reading as nonsense — unlike the reference material's ~39 bespoke
 *   pairs, which are reactions to their own directive and don't recombine safely.
 *
 * All entries: lowercase-first, no trailing terminal punctuation (composeWhimsyPost.ts appends
 * it), internal punctuation kept where it's part of the joke.
 */

export const WHIMSY_POOL_A: readonly string[] = [
  'reply "haha" to the message you left on read',
  "do NOT buy the $47 candle",
  "stretch your neck",
  "avoid the blue pen",
  "check the second drawer",
  "someone thinks you're cute. No further information",
  "someone in your contacts has a crush on you. Guess who",
  "a stranger almost said hi to you today. Almost",
  "your crush is thinking about you right now. Allegedly",
  "someone saved your number under a nickname. It's a good one",
  "you're someone's type today. No pressure",
  "someone reread your last text twice",
  "you're on someone's mind. Don't ask who",
  "someone almost texted you first. Almost",
  "someone misses you right now. They won't say it",
  "today is a good day to dramatically leave a group chat",
  "clean your keyboard",
  "wear the shirt with the small stain. Trust me",
  "buy bananas",
  "bananas are involved",
  "check the back seat",
  "buy the expensive yogurt",
  "put the mug in the sink",
  "change your bedsheets",
  "take the long way home",
  "buy new socks",
  "drink more water",
  "don't answer that text",
  "get a little treat",
  "open the window",
  "wear something orange",
  "clean your phone screen",
  "leave work on time",
  "eat something green",
  "charge your headphones",
  "hide the good snacks",
  "stand outside for a minute",
  "buy one unnecessary spoon",
  "walk into a bookstore",
  "change your wallpaper",
  "look under the bed",
  "buy a tiny notebook",
  'say "interesting" and leave',
  "wash the cup on your desk",
  "replace your toothbrush",
  "check the back pocket",
  "eat the banana before it goes bad",
  'text "on my way" slightly earlier than usual',
  "finally use the fancy soap",
  "unsubscribe from one email list",
  "buy the red one",
  "sit somewhere you don't normally sit",
  "wear the outfit you were saving",
  "don't take the second elevator",
  "say no to the extra sauce",
  "check your left pocket",
  "leave five minutes early",
  "don't make plans after 9",
  "avoid the group chat today",
  "trust the vending machine",
  "don't go back for the charger",
  "order fries",
  "leave the party before midnight",
  "bring an umbrella. You won't need it",
  "throw away the receipt",
  "water the thing you keep meaning to water",
  "wear the blue shirt",
  "sharpen a pencil",
  "put it back!",
  "close the tab",
  "eat the orange before it goes bad",
  "forgive the typo",
  "check your tire pressure",
  "buy stamps",
  "move the chair six inches to the left",
  "put your phone on silent and mean it",
  "don't reply yet",
  "wash the spoon",
  "check your bookmarks",
  'text your brother "hey"',
  "replace the dead bulb",
  "leave one thing unfinished",
  "unclench your jaw",
  "return the borrowed book",
  "get quarters",
  "buy a cucumber",
  "say good morning to the dog",
  "the answer is in your junk drawer",
  "bring a jacket anyway",
  "stop rereading it",
  "make the appointment",
  "let the laundry sit for one more day",
  "call your mom before Sunday",
  "change your password",
  "take cash",
  "buy the smaller one",
  "check the mailbox",
  "apologize to the plant. Again",
  "put gas in the car",
  "don't buy another candle",
  "write it down",
  "wear something purple",
  "send the post",
  "throw out the expired sauce",
  "straighten the picture frame",
  "stop checking the weather",
  "bring a pen",
  "go to bed at 10:47",
  "learn where the batteries are kept",
  "open the curtains",
  "look behind you",
  "say good night to the cat",
  "eat the leftovers",
  "avoid the mall",
  "take the flower out of the plastic",
  "make the reservation",
  "put the grape back",
  "investigate the spoon",
  "stop teaching the pigeon",
  "hide the good scissors",
  "buy a ceremonial onion",
  "forgive the mailbox",
  "don't spend that money",
  "rotate the mattress 4 degrees",
  "don't let the bagel win",
  "acquire a small bell",
  "inspect the ceiling fan",
  "name the cucumber",
  "apologize to a chair",
  "take the sticker off the banana",
  "put one sock in your pocket",
  "check if the moon followed you",
  "feed the imaginary horse",
  "purchase a suspiciously small hat",
  "rearrange the condiments by emotional importance",
  "ask the elevator how it's doing",
  "throw away the mysterious key",
  "carry a potato for seven blocks",
  "make eye contact with the Roomba",
  "put a spoon in the freezer",
  "stand in the doorway and reconsider soup",
  'stop saying "interesting" to the microwave',
  "count the pigeons. Ignore the result",
  "move one grape to a different bowl",
  "check your pockets for evidence",
  "acquire a map of somewhere you aren't going",
  "dust the object you don't own",
  "ask a stranger if they have seen your horse",
  "put the plant somewhere it can think",
  "don't trust the second banana",
  "wear two different socks on purpose",
  "place a coin beneath the pillow",
  "compliment a parking meter",
  "buy a lemon and give it a name you regret",
  "inspect the yogurt",
  "avoid the third aisle",
  "bring a fork to a non-fork situation",
  "alphabetize your problems",
  "put the remote in the refrigerator. Briefly",
  "ask the plant for its side of the story",
  "say zucchini and leave",
  "purchase an egg you do not need",
  "fold the receipt into a tiny hat",
  "tell the sink you forgive it",
  "wear sunglasses indoors for fifteen minutes",
  "rotate your pillow and see what happens",
  "update your playlist",
  "put your hand on the wall. It knows",
  "eat the crouton",
  "buy a cabbage",
  "do not challenge the lemon",
  "release the moth",
  "turn the napkin upside down",
  "keep the receipt",
  "bring a small rock",
  "put the banana in the drawer",
  "text someone you haven't spoken to in 3-7 business months",
  "delete one screenshot",
  "spend $8 on something completely unnecessary",
  "open the email you've been avoiding",
  "wash your favorite hoodie",
  "compliment yourself out loud. No witnesses required",
  "ignore them",
  "compliment their outfit",
  "reorganize one drawer and absolutely nothing else",
  "take a different route home",
  "buy the slightly nicer version",
  "stare out a window for 4 minutes",
  "wash your water bottle",
  "move one piece of furniture",
  "eat the slightly weird fruit",
  "replace your phone wallpaper",
  "open the drawer you avoid",
  "take the scenic route home",
  'wear the shirt you save for "something"',
  "put your keys somewhere unusual",
  "water the plant",
  "rearrange your bedside table",
  "use the nice mug",
  "learn the name of a nearby tree",
  "put coins in a jar",
  "go outside without headphones",
  "check the expiration date on your ranch",
  "buy a pen that writes slightly too smoothly",
  "fold one fitted sheet correctly",
  "eat breakfast standing up",
  "clean under the bed",
  "put your change in alphabetical order",
  "read the last page of an old notebook",
  "put your alarm five minutes earlier",
  "eat something with dill",
  "rearrange your apps",
  "carry a coin tomorrow",
  "clean your glasses",
  "open a window for exactly seven minutes",
  // The feature's original two example lines (kept verbatim as fixed compound entries, not split
  // into directive+punchline — their punchlines are specific callbacks to their own directive
  // ("feet" <-> socks, "which one" <-> screenshot), so they can't join Pool B's cross-compatible
  // pool without producing nonsense pairings like "delete one screenshot. Your feet deserve a plot
  // twist."
  "buy new socks. Your feet deserve a plot twist",
  "delete one screenshot. You know which one",
];

/** Every directive here is written to combine sensibly with every punchline below — deliberately
 *  vaguer/more universal than the reference material's bespoke pairs, since these get freely
 *  cross-multiplied at compose time (unlike the feature's original two example lines, which are
 *  specific callbacks to their own directive and live as fixed compound entries in
 *  WHIMSY_POOL_A instead). */
export const WHIMSY_POOL_B_DIRECTIVES: readonly string[] = [
  "buy new socks",
  "delete one screenshot",
  "reorganize one shelf",
  "charge your phone past 20%",
  "wear the good shirt today",
  "answer the message you've been drafting",
  "clean one window",
  "throw out one expired thing",
  "say yes to the detour",
  "buy the thing you keep putting back",
];

export const WHIMSY_POOL_B_PUNCHLINES: readonly string[] = [
  "trust the process",
  "no further questions",
  "this is not a coincidence",
  "the universe is watching, keenly",
  "you'll know why later",
  "don't overthink it",
  "that's the whole prophecy",
  "this one is non-negotiable",
  "the timing is not an accident",
  "act like you knew all along",
  // §2 round 4: grown from 10 to 80 so the punchline-repeat cycle stretches to ~6-8 weeks at the
  // revised 5/day cadence, instead of ~4 days at 10. Every line below was checked against all of
  // WHIMSY_POOL_B_DIRECTIVES for cross-compatibility, not just written in isolation — see
  // ase-bot-fragment-pool-verification memory for why that check matters.
  "you don't need to understand it",
  "just go with it",
  "this is bigger than you think",
  "some things don't need a reason",
  "resist the urge to ask why",
  "you'll thank yourself later",
  "this doesn't need footnotes",
  "this is the whole point",
  "don't ruin it by thinking too hard",
  "the stars insist",
  "this has cosmic backing",
  "the moon approves",
  "something bigger is in on this",
  "consider it written in the sky",
  "the planets agreed on this one",
  "this one has celestial clearance",
  "call it fate, loosely",
  "the universe has notes, but they're kind",
  "that's all you get",
  "the details are classified",
  "no further comment",
  "some things stay unexplained",
  "that's between you and the universe",
  "questions will not be taken",
  "that's the whole transmission",
  "this was always going to happen today",
  "today picked you back",
  "you were due for this",
  "this one's been building",
  "right on schedule",
  "the timing checks out",
  "this was always the plan",
  "consider the timing intentional",
  "ask again in a week",
  "future you already gets it",
  "this pays off eventually",
  "you'll look back on this fondly",
  "give it a few days",
  "this one has a delay",
  "patience is doing some work here",
  "there is no alternate option",
  "this isn't up for debate",
  "consider this final",
  "no substitutions",
  "this is the only path forward today",
  "there's no version where you skip this",
  "this one's locked in",
  "you already suspected this",
  "this confirms what you already knew",
  "your gut already agreed",
  "you've been waiting for permission",
  "consider yourself blessed, mildly",
  "this one's a gift, no returns",
  "take the win",
  "this counts as good news",
  "enjoy this one, no catch",
  "this is a freebie",
  "no strings, promise",
  "this one's on the house",
  "small miracles count too",
  "this one skips the line",
  "no notes",
  "this is your sign, apparently",
  "treat this as confirmed",
  "this one's rare, enjoy it",
  "consider this a nudge, not a demand",
  "this comes with quiet approval",
  "no drama, just do it",
  "this one's got good energy",
  "trust it more than usual today",
];

/** The full directive-only pool (§2 round 3: "Pool B's directives fold into Pool A"). */
export const WHIMSY_DIRECTIVE_POOL: readonly string[] = [...WHIMSY_POOL_A, ...WHIMSY_POOL_B_DIRECTIVES];
